name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'server/**' # Path to the server code directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t darshanbennur/chai-trade-backend:latest .
          docker push darshanbennur/chai-trade-backend:latest
